### ISSUE TITLE
Add theming support.

### ISSUE THREAD

**Issue by mcapu** [TF2Stadium/Frontend#10]
Suggestion:

1. Create a file called `_colors.scss` that includes every color setting in the project.
2. Create a file for the theme (probably start with a dark theme) that includes the same settings nested inside a CSS class (for example, `.dark-theme`).
3. Use a controller to add a class to the body. That way, the color settings should be applied by just specificity.

**Comment by tehp** [comment]
I can setup a theme stealing CSS from the pages for a theme class. 

Do you want a dark theme and a light theme?
Sometimes it is better for the whole site to run the same theme for a familiar look and feel.

**Comment by DSchalla** [comment]
While I would favor it too, it was requested several times and we will have a option to switch to the dark theme. Thats at least the current plan

**Comment by mcapu** [comment]
We should have a default theme, which is what we have right now.

At the moment there's only a need for a dark theme, which is something we've been asked to implement in several occasions.

**Comment by tehp** [comment]
I've got a few questions, but I will wait until I can ask them on Slack.

Thanks, 
Mac Craig
