### ISSUE TITLE
Lobby-create fails to show options sometimes.

### ISSUE THREAD

**Issue by mcapu** [TF2Stadium/Frontend#125]
I don't know how to reproduce or have any clue about what's causing it, but setting one of the options makes the next steps be empty. It happens with maps, leagues and whitelists.

**Comment by gpittarelli** [comment]
I believe this was fixed by:

https://github.com/TF2Stadium/Frontend/commit/1f1aa2c4da5e677aefa683323f8cf68a3dc32e11
