### ISSUE TITLE
Current lobby count doesnt sync with filter

### ISSUE THREAD

**Issue by HenriBeck** [TF2Stadium/Frontend#273]
http://imgur.com/IT6vuCS

**Comment by HenriBeck** [comment]
You are using the filter lobbies here:
https://github.com/TF2Stadium/Frontend/blob/dev/src/app/pages/lobby/list/lobby-list.html#L33

But you dont use them here:
https://github.com/TF2Stadium/Frontend/blob/dev/src/app/pages/lobby/list/lobby-list.html#L38-L42

**Comment by gpittarelli** [comment]
Sorry, could you clarify exactly what the issue is?

**Comment by HenriBeck** [comment]
Sorry for the late response.

I didnt read the sentence beneath it.

Sorry for bothering you
