### ISSUE TITLE
Add Left Sidebar to Settings Page (like Lobby Create)

### ISSUE THREAD

**Issue by DSchalla** [TF2Stadium/Frontend#36]

**Comment by mcapu** [comment]
Added in the following commits: 0e399be1c055706cc6e7f768be37a12c0c706a15 f348f3f86503fe259a43729658f86f7ca3b123d6 d2ba0851fdef30d8f9ed4d362f33cae3aba06022 c63322edf389e443278e3f5d7fb078069080554b b15fafe538e739828c61c433a07dd4f439bd53f0 a53404f5bd4b9d116992ff92e9c872ca0d6df546
