### ISSUE TITLE
Is joining the TF2Stadium team as  junior Node developer a possibility?

### ISSUE THREAD

**Issue by bnb** [TF2Stadium/Frontend#7]
Hey there.

I go by Haethcliff in TF2, and Tierney in real life. I'm an aspiring Node developer who has been very active in the community - I'm a member of the io.js Evangelism WG, Websuite WG, and Roadmap WG, I have spent a lot of time working on learning Node, and am a general lover of it. 

I was wondering if it would be possible to join up with you guys as a Node developer. I'm essentially looking for something like a mentor - I've spent a lot of time learning JS on sites like Codecademy, Code School, and all the tutorial sites, but haven't broken the barrier between understanding functions, if/else, loops, callbacks, etc. to actually being able to use them to build functional programs that complete a task. 

I have a very deep interest in TF2-centric web applications. I have several ideas which might jive well with TF2Stadium. One that I think might be super popular if implemented early on is a resume-style site for comp players to show teams about their skills, attributes, and stats.

If you guys are willing to have another person on the team, let me know: `bitnb``@``subvertising.org`

**Comment by DSchalla** [comment]
Hi @bnb,
we were uncertain if you want to contribute to the Frontend or Backend?  Our backend is written in Golang, not NodeJS and our frontend is using AngularJS.

Regards,
Daniel

**Comment by bnb** [comment]
Ah, I assumed it was Node because of the package.json - what stack are you running for the Frontend? I intended to indicate that I'm interested on working with the Frontend, given that I thought it was a Node app. 

Either way, I wouldn't be adverse to learning Go. I know many people who use Go in production and actively develop with it, and have previously suggested that I use it. I wouldn't want to put a burden on you if I were to learn it, though, so if it _is_ in the cards, we'd structure it with that in mind.

Also - thanks for taking the time to respond. I know you must be crazy busy trying to get it up. Again, I'd love to help in any way I can - I also have a good amount of professional technical writing, creating written content like articles and social media interactions.

**Comment by mcapu** [comment]
Please see https://github.com/TF2Stadium/Frontend/issues/9
