### ISSUE TITLE
Getting Involved

### ISSUE THREAD

**Issue by tehp** [TF2Stadium/Frontend#9]
Hello TF2S team,

I am interested in getting involved in the frontend of the site.
I was wondering if you have a Slack team, Gitter, or some way for me to contact the dev team since your steam group doesn't seem right. 

I didn't want to dive in and start making changes without knowing the roadmap, and where my efforts could be used.

Thanks, 
Mac Craig

**Comment by DSchalla** [comment]
Hi Mac,

Thanks for being interested to help us out! I agree, the Steam Group wouldn't be the proper place. :)

Yup we got a slack team, shall I send you an invite on the mail in your Github Profile? Then we can talk a little bit.

Best Regards,
Daniel

**Comment by mcapu** [comment]
Hello, Mac

I've created an issue regarding themes at https://github.com/TF2Stadium/Frontend/issues/10. We're in the middle of reformatting some of the code, but that's something I think you can help us with at the moment until we push our changes to the repo.

Thanks for asking!

Capu

**Comment by tehp** [comment]
That would be great.

Thanks, 
Mac Craig

**Comment by tehp** [comment]
@mcapu I will give that a read and contact you guys via Slack.

Mac Craig
